<a href="https://colab.research.google.com/github/Jenish-Mhrzn/Machine_learning/blob/main/Introduction/numpy_5th_sem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to numpy

#what we will cover?
  .Creating arrays 👍
  .Multidimensional array
  .Randomly generated arrays
  .Element wise operation
  .Summarizing operations

###Single dimension array

In [ ]:
import numpy as np

In [ ]:
#create an array with all the element to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#create an array with all the element to be 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#create an array of size 10 with all elemnts 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create an array with evenly spaced number within a specifies range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

###Multi dimension array

In [ ]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0, 1]=20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
a[2] = [1, 1, 1]
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [ ]:
a[:, 2] = [2, 2, 2]
a

array([[1, 2, 2],
       [4, 5, 2],
       [1, 1, 2]])

In [ ]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

###Randomly generated arrays
  .Numpy can create arrays filled with random numbers
  .To ensure the reporoducibility, yoc can set a seed using ```np.random.seed()```. it will generate the exact same random number for each executions
  .if you remove or change the seed values, the sequence of random number will be changed.

In [ ]:
np.random.rand(5)

array([0.11928213, 0.11477858, 0.21523108, 0.62361979, 0.37340574])

In [ ]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [ ]:
np.random.randn(5, 2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [ ]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[24,  1],
       [17, 54],
       [16, 41],
       [20, 31],
       [24, 67]])

###Elemnt wise operation on entire arrays element by element

In [3]:
import numpy as np
a=np.arange(5)
a


array([0, 1, 2, 3, 4])

In [4]:
b=(10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [5]:
#comparision operations
a

array([0, 1, 2, 3, 4])

In [6]:
a >=2

array([False, False,  True,  True,  True])

In [7]:
a >b

array([False, False, False, False, False])

In [8]:
# sumarizing of the data
# Numpy provides function for sumarizing array data
a

array([0, 1, 2, 3, 4])

In [9]:
#standard deviation
a.std()

1.4142135623730951

In [10]:
a.min()

0

In [11]:
a.max()

4

In [12]:
a.sum()

10